### ISSUE TITLE
Error in 'npm install' on web_server

### ISSUE THREAD

**Issue by csima** [adobe/Marinus#1]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@coralui%2fcoralui - Not found
npm ERR! 404
npm ERR! 404  '@coralui/coralui@^3.30.8' is not in the npm registry.

**Comment by puhley** [comment]
Thanks for the report. I know what the issue is and it will take me a few days to fix. I'll report back soon.

**Comment by puhley** [comment]
I just added a commit which will hopefully clear up this issue. Please do a new checkout and let me know if you still have issues during the setup.

**Comment by puhley** [comment]
Fixed with commit #c6b4258
