### ISSUE TITLE
Migrate upload_akamai_data.py from static list (out of date) to dynamic list

### ISSUE THREAD

**Issue by bionicspy** [adobe/Marinus#10]
### Expected behaviour
periodic updates based on vendor provided information
https://techdocs.akamai.com/origin-ip-acl/docs/update-your-origin-server

### Actual behaviour
Set list on IP ranges hard coded in update code

#### Sample code/data that illustrates the problem
```
    AKAMAI_DATA["ranges"] = []
    AKAMAI_DATA["ranges"].append(
        {"cidr": "2.23.144.0/20", "ip_range": "2.23.144.0 - 2.23.159.255"}
    )
```

**Comment by puhley** [comment]
Thank you for raising this issue and I apologize for the delay in my response. I have recently pushed an update to dynamically fetch the data from Akamai: https://github.com/adobe/Marinus/commit/2354d7f981a14d12964d1d39358b98c1f15d434a
